class BirthdayParty {
    // Generated by the @InjectedDependencies macro

    typealias Dependencies: any ClownManager.Dependency & HONKDevice.Dependency

    private let dependencies: Dependencies

    // An unforgettable event happens here.
}
