public class BirthdayParty {
    // Generated by the @InjectedDependencies macro

    public typealias Dependencies: any ClownManager.Dependency & HONKDevice.Dependency

    internal let dependencies: Dependencies

    // An unforgettable event happens here.
}
