name: Routine Validation

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  format-validation:
    name: Format
    runs-on: macos-13
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_14.3.0.app/Contents/Developer
      - name: Verify Format
        run: swiftformat . --lint --dryrun
  linter-validation:
    name: Linter
    runs-on: macos-13
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_14.3.0.app/Contents/Developer
      - name: Verify Format
        run: swiftlint . --quiet
